birdclassification/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from home import views
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.renderHome, name='renderHome'), 
    path('add_bird_species/', views.add_bird_species, name='add_bird_species'),  
    path('species_detail/<int:species_id>/', views.species_detail, name='species_detail'),
    path('about',views.about, name='about'),
]

home/models.py
# models.py

from django.db import models
from django.urls import reverse
from django.utils import timezone


class BirdSpecies(models.Model):
    STATUS_CHOICES = [
        ('LC', 'Least Concern'),
        ('NT', 'Near Threatened'),
        ('VU', 'Vulnerable'),
        ('EN', 'Endangered'),
        ('CR', 'Critically Endangered'),
    ]
    My_choice =[
        ('LC', 'Least Concern'),
        ('NT', 'Near Threatened'),
        ('VU', 'Vulnerable'),
        ('EN', 'Endangered'),
        ('CR', 'Critically Endangered'),
    ]
    

    status_code = models.CharField(max_length=10, choices=STATUS_CHOICES)
    common_name = models.CharField(max_length=100, unique=True)
    scientific_name = models.CharField(max_length=100)
    bird_description = models.TextField(blank=True)
    current_status = models.CharField(max_length=10,choices= My_choice)
    wiki_link = models.URLField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.common_name

class ClassifiedImage(models.Model):
    image = models.ImageField(upload_to='classified_images/')
    predicted_species = models.ForeignKey(BirdSpecies, on_delete=models.CASCADE, null=True)
    classified_at = models.DateTimeField(auto_now_add=True)
    confidence = models.FloatField(blank=True, null=True)

    def __str__(self):
        return f'{self.predicted_species.common_name} - {self.classified_at}'

    def get_absolute_url(self):
        return reverse('classified-image-detail', args=[str(self.id)])

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.core.files.storage import default_storage
from .models import ClassifiedImage, BirdSpecies
from .ml_model import predictClassLabel
from django.http import HttpResponseBadRequest, HttpResponseServerError
import logging
from datetime import datetime

logger = logging.getLogger(__name__)

def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

def renderHome(request):
    predicted_species = None
    image_url = None

    try:
        if request.method == 'POST':
            submitted_image = request.FILES.get('image')

            if submitted_image:
                image_path = default_storage.save(f'classified_images/{submitted_image.name}', submitted_image)
                predicted_species_name = predictClassLabel(submitted_image)

                if predicted_species_name is not None:
                    predicted_species, _ = BirdSpecies.objects.get_or_create(common_name=predicted_species_name)

                    # Save the classified image to the database
                    classified_image = ClassifiedImage.objects.create(
                        image=image_path,
                        predicted_species=predicted_species
                    )

                    # Generate the correct image URL using the 'url' template tag
                    image_url = f'{settings.MEDIA_URL}{image_path}'
                    return redirect('species_detail', species_id=predicted_species.id)
                else:
                    error_message = "Model not confident. Prediction probability below threshold."
                    styled_error_message = f"<div style='position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); text-align: center;'><p style='font-weight: bold; font-size: 60px;'>{error_message}</p></div>"
                    return HttpResponseBadRequest(styled_error_message)

    except Exception as e:
        logger.error(f"Error during image processing: {e}", exc_info=True)
        return HttpResponseServerError("Internal Server Error")

    context = {
        'predicted_species': predicted_species,
        'image_url': image_url,
    }
    return render(request, 'home.html', context)


def add_bird_species(request):
    if request.method == 'POST':
       
        status_code = request.POST.get('status_code')
        common_name = request.POST.get('common_name')
        scientific_name = request.POST.get('scientific_name')
        bird_description = request.POST.get('bird_description')
        current_status = request.POST.get('current_status')
        wiki_link = request.POST.get('wiki_link')

    
        if status_code is not None:
          
            BirdSpecies.objects.create(
                status_code=status_code,
                common_name=common_name,
                scientific_name=scientific_name,
                bird_description=bird_description,
                current_status=current_status,
                wiki_link= wiki_link
            )

            # return redirect('/')

    return render(request, 'add_bird_species.html')

def species_detail(request, species_id):
    species = get_object_or_404(BirdSpecies, pk=species_id)
    classified_image = ClassifiedImage.objects.filter(predicted_species=species).order_by('-classified_at').first()
    current_time = datetime.now().strftime('%Y-%m-%d %H:%M')
    context = {
        'species': species,
        'classified_image': classified_image,
        'image_url': classified_image.image.url if classified_image else None,
        'current_time': current_time,
    }

    return render(request, 'species_detail.html', context)

templates/about.html
{% extends 'base.html' %}
{% block title %}About Us{% endblock %}
{% block content %}
<div class="ml-4 md:mx-16 md:ml-16 mt-8">
  <h1 class="text-2xl font-bold mb-2">Introduction</h1>
  <p class="mb-6">
    Welcome to our Bird Species Prediction Project! This project utilizes
    machine learning to predict the Endangered species of a bird based on the provided
    image.The list of Endangered bird species is collected from the Nepal's National Red List of Birds journal. The
    dataset for this project is collected from ebird website.
  </p>

  <h3 class="text-2xl font-bold mb-2">How It Works</h3>
  <p class="mb-6">
    Our model is trained using a dataset of 38 endangered bird species of Nepal.
    It leverages deep learning techniques to analyze and classify images of
    birds, providing accurate predictions of the species.
  </p>

  <h3 class="text-2xl font-bold mb-2">Supported Bird Species</h3>
  <p class="mb-6">
    The model supports following <span class="font-bold">Endangered Bird Species</span> of Nepal:
  </p>

  <ul class="flex flex-row md:justify-between flex-wrap" id="species-container"></ul>

  <h3 class="text-2xl font-bold mb-2">Technologies Used</h3>
  <ul class="list-disc ml-4 md:ml-8 mb-6">
    <li>Convolution Neural Network (CNN) for Model Building</li>
    <li>Django Framework</li>
    <li>Django REST framework</li>
    <li>TensorFlow for machine learning</li>
    <li>Tailwind Css for Styling</li>
  </ul>
  <div class="mb-2">
    <h1 class="text-2xl font-bold">References</h1>
    <ul class="list-disc ml-4 md:ml-8 mb-6 w-full">
      <li class="my-3">Journal: <a href="http://doi.org/10.11609/jott.2855.9.1.9700-9722 " target="_blank"
          class="w-52  p-1 font-bold rounded-md text-black hover:text-red ">Click
          Here!</a> </li>
      <li class="mt-5">ebird: <a href="https://media.ebird.org/catalog?sort=rating_rank_desc&mediaType=photo " target="_blank"
          class="w-52  p-1 font-bold rounded-md text-black hover:text-red ">Click
          Here!</a> </li>
    </ul>
  </div>
</div>

<script>
  const birdSpecies = [
    {
      commonName: "Abbott`s Babbler",
      scientificName: "Malacocincla abbotti",
      url: "https://en.wikipedia.org/wiki/Abbott%27s_babbler"
    },
    {
      commonName: "Black Bittern",
      scientificName: "Dupetor flavicollis",
      url: "https://en.wikipedia.org/wiki/Black_bittern"
    },
    {
      commonName: "blue-eared Kingfisher",
      scientificName: "Alcedo meninting",
      url: "https://en.wikipedia.org/wiki/Blue-eared_kingfisher"
    },
    {
      commonName: "Blue-naped Pitta",
      scientificName: "Pitta nipalensis",
      url: "https://en.wikipedia.org/wiki/Blue-naped_pitta"
    },
    {
      commonName: "Broad-billed Warbler",
      scientificName: "Tickellia hodgsoni",
      url: 'https://en.wikipedia.org/wiki/Broad-billed_warbler'
    },
    {
      commonName: "Cheer Pheasant",
      scientificName: "Catreus wallichii",
      url: 'https://en.wikipedia.org/wiki/Cheer_pheasant'
    },
    {
      commonName: "Chestnut Munia",
      scientificName: "Lonchura atricapilla",
      url: 'https://en.wikipedia.org/wiki/Chestnut_munia'
    },
    {
      commonName: "Cinereous Vulture",
      scientificName: "Aegypius monachus",
      url: 'https://en.wikipedia.org/wiki/Cinereous_vulture'
    },
    {
      commonName: "Golden Babbler",
      scientificName: "Stachyris chrysaea",
      url: 'https://en.wikipedia.org/wiki/Golden_babbler'
    },
    {
      commonName: "Goulds Shortwing",
      scientificName: "Brachypteryx stellata",
      url: 'https://en.wikipedia.org/wiki/Gould%27s_shortwing'
    },
    {
      commonName: "Great Bittern",
      scientificName: "Botaurus stellaris",
      url: 'https://en.wikipedia.org/wiki/Eurasian_bittern'
    },
    {
      commonName: "Great Hornbill",
      scientificName: "Buceros bicornis",
      url: 'https://en.wikipedia.org/wiki/Great_hornbill'
    },
    {
      commonName: "Great Slaty Woodpecker",
      scientificName: "Mulleripicus pulverulentus",
      url: 'https://en.wikipedia.org/wiki/Great_slaty_woodpecker'
    },
    {
      commonName: "Ibisbill",
      scientificName: "Ibidorhyncha struthersii",
      url: 'https://en.wikipedia.org/wiki/Ibisbill'
    },
    {
      commonName: "Indian Courser",
      scientificName: "Cursorius coromandelicus",
      url: 'https://en.wikipedia.org/wiki/Indian_courser'
    },
    {
      commonName: "Indian Grassbird",
      scientificName: "Graminicola bengalensis",
      url: 'https://en.wikipedia.org/wiki/Indian_grassbird'
    },
    {
      commonName: "Indian Nightjar",
      scientificName: "Caprimulgus asiaticus",
      url: 'https://en.wikipedia.org/wiki/Indian_nightjar'
    },
    {
      commonName: "Knob-billed Duck",
      scientificName: "Sarkidiornis melanotos",
      url: 'https://en.wikipedia.org/wiki/Knob-billed_duck'
    },
    {
      commonName: "Northern Pintail",
      scientificName: "Anas acuta",
      url: 'https://en.wikipedia.org/wiki/Northern_pintail'
    },
    {
      commonName: "Painted Stork",
      scientificName: "Mycteria leucocephala",
      url: 'https://en.wikipedia.org/wiki/Painted_stork'
    },
    {
      commonName: "Purple Cochoa",
      scientificName: "Cochoa purpurea",
      url: 'https://en.wikipedia.org/wiki/Purple_cochoa'
    },
    {
      commonName: "Red-headed Trogon",
      scientificName: "Harpactes erythrocephalus",
      url: 'https://en.wikipedia.org/wiki/Red-headed_trogon'
    },
    {
      commonName: "Red-headed Vulture",
      scientificName: "Sarcogyps calvus",
      url: 'https://en.wikipedia.org/wiki/Red-headed_vulture'
    },
    {
      commonName: "Red-necked Falcon",
      scientificName: "Falco chicquera",
      url: 'https://en.wikipedia.org/wiki/Red-necked_falcon'
    },
    {
      commonName: "Ruby-cheeked Sunbird",
      scientificName: "Anthreptes singalensis",
      url: 'https://en.wikipedia.org/wiki/Ruby-cheeked_sunbird'
    },
    {
      commonName: "Rusty-fronted Barwing",
      scientificName: "Actinodura egertoni",
      url: 'https://en.wikipedia.org/wiki/Rusty-fronted_barwing'
    },
    {
      commonName: "Saker Falcon",
      scientificName: "Falco cherrug",
      url: 'https://en.wikipedia.org/wiki/Saker_falcon'
    },
    {
      commonName: "Silver-eared Mesia",
      scientificName: "Leiothrix argentauris",
      url: 'https://en.wikipedia.org/wiki/Silver-eared_mesia'
    },
    {
      commonName: "Slaty-legged Crake",
      scientificName: "Rallina eurizonoides",
      url: 'https://en.wikipedia.org/wiki/Slaty-legged_crake'
    },
    {
      commonName: "Spot-bellied Eagle Owl",
      scientificName: "Bubo nipalensis",
      url: 'https://en.wikipedia.org/wiki/Spot-bellied_eagle-owl'
    },
    {
      commonName: "Sultan Tit",
      scientificName: "Melanochlora sultanea",
      url: 'https://en.wikipedia.org/wiki/Sultan_tit'
    },
    {
      commonName: "Swamp Francolin",
      scientificName: "Francolinus gularis",
      url: 'https://en.wikipedia.org/wiki/Swamp_francolin'
    },
    {
      commonName: "Tawny-bellied Babbler",
      scientificName: "Dumetia hyperythra",
      url: 'https://en.wikipedia.org/wiki/Tawny-bellied_babbler'
    },
    {
      commonName: "Thick-billed Green Pigeon",
      scientificName: "Treron curvirostra",
      url: 'https://en.wikipedia.org/wiki/Thick-billed_green_pigeon'
    },
    {
      commonName: "White-throated Bulbul",
      scientificName: "Alophoixus flaveolus",
      url: 'https://en.wikipedia.org/wiki/White-throated_bulbul'
    },
    {
      commonName: "White-throated Bushchat",
      scientificName: "Saxicola insignis",
      url: 'https://en.wikipedia.org/wiki/White-throated_bush_chat'
    },
    {
      commonName: "Yellow-rumped Honeyguide",
      scientificName: "Indicator xanthonotus",
      url: 'https://en.wikipedia.org/wiki/Yellow-rumped_honeyguide'
    },
    {
      commonName: "Yellow-vented Warbler",
      scientificName: "Phylloscopus cantator",
      url: 'https://en.wikipedia.org/wiki/Yellow-vented_warbler'
    }

  ];

  function createBirdSpeciesHTML(species) {
    return `
          <a href="${species.url}" target="_blank" class="w-2/5 mr-auto  md:w-auto mb-3 p-2 rounded-lg border-4 hover:text-white hover:bg-black hover:border-none hover:duration-300 hover:ease-in-out">
              <li class="text-lg font-bold">${species.commonName}</li>
              <li class="text-sm">${species.scientificName}</li>
          </a>
      `;
  }
  const container = document.getElementById("species-container");
  birdSpecies.forEach(species => {
    const speciesHTML = createBirdSpeciesHTML(species);
    container.innerHTML += speciesHTML;
  });
</script>

{% endblock %}

templates/add_bird_species.html
{% extends 'base.html' %}
{% block title %}Add species{% endblock %}
{% block content %}

<div class="container mx-auto my-8  flex flex-col items-center justify-center">
    <!-- <div class=" mb-5">
        <h1 class="font-bold text-2xl md:text-3xl m-0  text-slate-700 uppercase">ADD BIRD SPECIES DETAILS</h1>
    </div> -->
    <form method="post" action="{% url 'add_bird_species' %}" class="w-full  bg-white rounded-md shadow-md p-8 ">
        {% csrf_token %}

        <div class="mb-1">
            <label for="status_code" class="block text-gray-700 text-sm font-bold mb-2">Status Code:</label>
            <select id="status_code" name="status_code" required
                    class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500">
                <option value="LC">LC</option>
                <option value="NT">NT</option>
                <option value="VU">VU</option>
                <option value="EN" selected>EN</option>
                <option value="CR">CR</option>
            </select>
        </div>

        <div class="mb-1">
            <label for="current_status" class="block text-gray-700 text-sm font-bold mb-2">Current Status:</label>
            <select id="current_status" name="current_status" required
                    class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500">
                <option value="LC">LC</option>
                <option value="NT">NT</option>
                <option value="VU">VU</option>
                <option value="EN" selected>EN</option>
                <option value="CR">CR</option>
            </select>
        </div>

        <div class="mb-1">
            <label for="common_name" class="block text-gray-700 text-sm font-bold mb-2">Common Name:</label>
            <input type="text" id="common_name" name="common_name" required
                   class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500">
        </div>

        <div class="mb-1">
            <label for="scientific_name" class="block text-gray-700 text-sm font-bold mb-2">Scientific Name:</label>
            <input type="text" id="scientific_name" name="scientific_name" required
                   class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500">
        </div>

        <div class="mb-1">
            <label for="bird_description" class="block text-gray-700 text-sm font-bold mb-2">Bird Description:</label>
            <textarea id="bird_description" name="bird_description" required
                      class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500"></textarea>
        </div>
        <div class="mb-1">
            <label for="wiki_link" class="block text-gray-700 text-sm font-bold mb-2">Wikipedia Link:</label>
            <textarea id="wiki_link" name="wiki_link" required
                      class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500"></textarea>
        </div>

       <div class="flex justify-center">
            <button
            type="submit"
            id="classifyButton"
            class="w-48 bg-purple-500 p-2 text-xl font-bold rounded-md text-white hover:bg-black hover:duration-500 hover:ease-in-out"
        >
            Submit
        </button>
       </div>
      </div>
        
    </form>
</div>

{% endblock %}

templates/base.html
{% load static tailwind_tags %}
{% load static %} 
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;400&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Stick&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/0.6.5/tailwind.min.css" rel="stylesheet" />
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
<title>Bird App | {% block title %}{% endblock %}</title>
{% tailwind_css %}
</head>

<body class="font-poppins">
  {% include 'navbar.html' %}

  {% block content %}
  {% endblock %}

  {% include 'footer.html' %}
  


</body>

</html>

templates/footer.html
<footer class="w-full md:mx-auto p-2 flex-row flex items-center justify-center flex-wrap ">
    <p>© 2024 <span class="font-bold text-sm md:text-md">Bird Speices Classification</span>. All rights reserved.</p>
</footer>

templates/home.html
{% extends 'base.html' %} 
{% block title %}Prediction{% endblock %}
{% block content %}


<div class="flex flex-col items-center justify-center min-h-[calc(100vh-25rem)]">
  <div>
    <h1 class="font-bold text-2xl md:text-3xl text-slate-700 inline-block text-center items-center md:mr-0">
      INSERT IMAGE TO PREDICT BIRD SPECIES
    </h1>
  </div>
  <div class=" p-6 md:p-10  w-full my-4">
    <form
      method="POST"
      id="image-upload-form"
      enctype="multipart/form-data"
      action="{% url 'renderHome' %}"
    >
    <!-- Image preview container -->
    <div id="img-show" class="mt-4 hidden ">
      <div class="flex items-center justify-center ">
        <img id="preview-img" alt="Image Preview" class="w-96 rounded-lg" />
      </div>
    </div>
      {% csrf_token %}
      <div class="flex flex-col justify-center items-center m-10 p-3">
        <input
          name="image"
          type="file"
          id="image-upload"
          accept="image/*"
          onchange="previewImage()"
          class="ml-5"
        />
        
        <button
          type="submit"
          id="classifyButton"
          class="w-48 bg-purple-500 mt-5 p-2 text-xl font-bold rounded-md text-white hover:bg-black hover:duration-500 hover:ease-in-out"
        >
          Predict Bird
        </button>
      </div>
      {% if predicted_species %}
      <strong
        ><p>Classified Image: {{ predicted_species.common_name }}</p></strong
      >
      {% endif %}
    </form>
  </div>
</div>

<script>
  function previewImage() {
      // Get the file input element
      var input = document.getElementById('image-upload');
      
      // Get the preview container and image elements
      var previewContainer = document.getElementById('img-show');
      var previewImage = document.getElementById('preview-img');

      // Check if a file is selected
      if (input.files && input.files[0]) {
          // Create a FileReader to read the selected image
          var reader = new FileReader();

          // Set the callback function when the image is loaded
          reader.onload = function (e) {
              // Set the source of the image preview
              previewImage.src = e.target.result;

              // Show the image preview container
              previewContainer.style.display = 'block';
          };

          // Read the selected image as data URL
          reader.readAsDataURL(input.files[0]);
      } else {
          // If no file is selected, hide the image preview container
          previewContainer.style.display = 'none';
      }
  }
</script>

{% endblock %}

templates/index.html
{% extends 'base.html' %} {% load static %} {% block title %}Home{% endblock %}
{% block content %}

<!-- <style>
  a {
 position: relative;
 display: inline-block;
 cursor: pointer;
 outline: none;
 border: 0;
 vertical-align: middle;
 text-decoration: none;
 background: transparent;
 padding: 0;
 font-size: inherit;
 font-family: inherit;
}

a.learn-more {
 width: 12rem;
 height: auto;
}

a.learn-more .circle {
 transition: all 0.45s cubic-bezier(0.65, 0, 0.076, 1);
 position: relative;
 display: block;
 margin: 0;
 width: 3rem;
 height: 3rem;
 background: #282936;
 border-radius: 1.625rem;
}

a.learn-more .circle .icon {
 transition: all 0.45s cubic-bezier(0.65, 0, 0.076, 1);
 position: absolute;
 top: 0;
 bottom: 0;
 margin: auto;
 background: #fff;
}

a.learn-more .circle .icon.arrow {
 transition: all 0.45s cubic-bezier(0.65, 0, 0.076, 1);
 left: 0.625rem;
 width: 1.125rem;
 height: 0.125rem;
 background: none;
}

a.learn-more .circle .icon.arrow::before {
 position: absolute;
 content: "";
 top: -0.29rem;
 right: 0.0625rem;
 width: 0.625rem;
 height: 0.625rem;
 border-top: 0.125rem solid #fff;
 border-right: 0.125rem solid #fff;
 transform: rotate(45deg);
}

a.learn-more .button-text {
 transition: all 0.45s cubic-bezier(0.65, 0, 0.076, 1);
 position: absolute;
 top: 0;
 left: 0;
 right: 0;
 bottom: 0;
 padding: 0.75rem 0;
 margin: 0 0 0 1.85rem;
 color: #282936;
 font-weight: 700;
 line-height: 1.6;
 text-align: center;
 text-transform: uppercase;
}

a:hover .circle {
 width: 100%;
}

a:hover .circle .icon.arrow {
 background: #fff;
 transform: translate(1rem, 0);
}

a:hover .button-text {
 color: #fff;
}
</style> -->

<div
  class="flex flex-col md:flex-row items-center justify-center m-10 min-h-[calc(100vh-25rem)]"
>
  <div class="mb-4 md:mb-0 md:mr-6">
    <img
      src="{% static 'images/hero.png' %}"
      alt=""
      class="h-48 md:h-[500px] w-auto object-cover"
    />
  </div>
  <div class="flex flex-col">
    <h1 class="font-bold text-2xl md:text-3xl mb-2 md:mb-4">
      Predict Endangered bird species instantly.
    </h1>
    <p class="text-lg flex flex-col md:flex-row md:items-center mt-4 md:mt-0">
      Explore nature effortlessly
      <!-- <a href="{% url 'renderHome' %}" class="text-purple text-3xl ml-2 hover:text-black duration-300"><i class="fas fa-check-square-o"></i></a> -->
      <a
        href="{% url 'renderHome' %}"
        class="md:ml-2 mt-2 md:mt-0  font-bold hover:text-white p-1 px-3 border-2 border-black rounded-md hover:bg-black hover:duration-500"
      >
        <i class="fas fa-check"></i>
        <span class="">Let's Predict</span>
      </a>
    </p>
  </div>
</div>
{% endblock %}

templates/navbar.html
{% load static %}

<header class=" md:flex md:items-center md:justify-between shadow-lg md:shadow-none p-4 pb-1 md:pb-4 m-5 rounded-md">
  
  <div class="flex items-center justify-between mb-4 md:mb-0 ">
    <a href="{% url 'index' %}">
      <h1 class="font-extrabold text-3xl md:ml-8 ">Endanger<span class="text-purple-500 font-extrabold">ED</span></h1>
    </a>

    <a class="text-black hover:text-purple md:hidden" href="#" id="menuToggle">
      <i class="fa fa-2x fa-bars"></i>
    </a>
  </div>

  <nav>
    <ul class="list-reset hidden md:flex md:items-center md:gap-8" id="navMenu">
      <li class="md:ml-4">
        <a class=" py-2 hover:font-bold hover:duration-300 md:p-0" href="{% url 'index' %}">
          Home
        </a>
      </li>
      <li class="md:ml-4">
        <a class=" py-2 hover:font-bold hover:duration-300 md:p-0" href="{% url 'renderHome' %}">
          Prediction
        </a>
      </li>
      <li class="md:ml-4">
        <a class=" py-2 hover:font-bold hover:duration-300 md:p-0" href="{% url 'about' %}">
          About Us
        </a>
      </li>
    </ul>
  </nav>
  
</header>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    var menuToggle = document.getElementById('menuToggle');
    var navMenu = document.getElementById('navMenu');

    menuToggle.addEventListener('click', function () {
      navMenu.classList.toggle('hidden');
    });

    
  });

</script>

templates/species_detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block title %}Species Detail{% endblock %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bird_species.css' %}" />

<div class="flex flex-col items-center">
    <div class="flex flex-col items-center justify-center">
        <div class="mb-5">
            <h1 class="font-bold text-3xl -m-3 text-slate-700 uppercase">BIRD SPECIES DETAILS</h1>
        </div>
        <div class="bg-purple-200 p-6 md:p-10 rounded-md md:mx-16">
            <div class="flex flex-col md:flex-row justify-center gap-6 md:gap-5">
                <div class="max-w-full md:max-w-1/2 h-auto md:h-48 overflow-hidden mb-4 md:mb-0 md:mr-6 rounded-md">
                    <img src="{{ image_url }}" alt="Classified Image" class="w-full h-full object-cover" />
                </div>
                <div class="flex flex-col gap-2 md:gap-4 mt-1">
                    <h2><span class="font-bold">Status Code:</span> {{ species.get_status_code_display  }}</h2>
                    <h3><span class="font-bold">Common Name:</span> {{ species.common_name }}</h3>
                    <h3><span class="font-bold">Scientific Name:</span> {{ species.scientific_name }}</h3>
                    <h3><span class="font-bold">Current Status: </span>{{ species.get_current_status_display }}</h3>
                </div>
            </div>
            <div class="flex flex-col  justify-center items-center mt-3">
                <div class="mb-3">
                    <p><span class="font-bold text-xl">Bird Description: </span>{{ species.bird_description }}</p>
                </div>
                <a href=" {{species.wiki_link}}" class="font-bold text-white p-2 bg-purple-500 rounded-md hover:bg-black hover:duration-500">{{species.common_name}} wikipedia</a>
                <div class="m-3">
                    <p>Classified At: {{ current_time }}</p>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}